Repository GSG-G7/far-nearer, pull requests merged in 2019-10, with the labels that each got.

#24 add readme file
  README.md
Labels: Awaiting Review

#28 project setup
  .eslintrc.js
  .gitignore
  .travis.yml
  client/.eslintrc.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/pages/AboutUs/index.js
  client/src/components/pages/AboutUs/style.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/Home/style.css
  client/src/components/pages/ViewBuildings/index.js
  client/src/components/pages/ViewBuildings/style.css
  client/src/components/utils/index.js
  client/src/index.js
  client/src/serviceWorker.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/emptyBuildings/index.js
  server/controllers/index.js
  server/controllers/mailList/index.js
  server/index.js
  server/models/config/index.js
  server/models/queries/emptyBuildings.js
  server/models/queries/mailList.js
  server/models/queries/users.js
  server/validation/index.js
  test/index.test.js
Labels: Done

#41 add vscode settings for eslint
  .vscode/settings.json
  package.json
Labels: Done

#42 mail list route
  package-lock.json
  server/app.js
  server/controllers/index.js
  server/controllers/mailList/index.js
  server/controllers/middleware/index.js
  server/models/queries/index.js
  server/models/queries/mailList.js
  server/validation/index.js
  server/validation/validateEmail.js
  test/mailList.test.js
Labels: Done

#44 Get empty building | Route
  server/controllers/emptyBuildings/get.js
  server/controllers/emptyBuildings/index.js
  server/controllers/index.js
  server/controllers/middleware/index.js
  server/models/queries/emptyBuildings.js
  server/models/queries/index.js
  test/emptyBuilding.test.js
Labels: Done

#46 axios installing and setup jsconfig
  client/.eslintrc.js
  client/jsconfig.json
  client/package-lock.json
  client/package.json
Labels: Done

#43 Report building route
  server/app.js
  server/controllers/emptyBuildings/index.js
  server/controllers/emptyBuildings/post.js
  server/controllers/index.js
  server/models/queries/emptyBuildings.js
  server/uploads/house.jpg
  server/validation/buildingSchema.js
  server/validation/index.js
  test/index.test.js
Labels: Done

#52 fix bug with error handling middleware using default statusCode
  server/controllers/middleware/index.js
Labels: Done

#54 Loading component
  client/src/components/utils/Loading/index.js
  client/src/components/utils/Loading/style.css
  client/src/components/utils/index.js
Labels: Awaiting Review

#57 Update airtable
  package-lock.json
  package.json
  server/models/queries/users.js
Labels: Awaiting Review

#60 Fix status code
  server/controllers/mailList/index.js
Labels: Awaiting Review

#59 Error page component
  client/src/assets/robot-error-codes.png
  client/src/components/pages/Error/index.js
  client/src/components/pages/Error/style.css
  client/src/components/utils/Loading/style.css
Labels: approved

#53 footer component
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/utils/Footer/Subscribe.js
  client/src/components/utils/Footer/index.js
  client/src/components/utils/Footer/style.css
Labels: approved
