Repository GSG-G7/far-nearer, pull requests merged in 2019-11, with the labels that each got.

#62 Install helmet
  package-lock.json
  package.json
  server/app.js
Labels: Awaiting Review

#65 Use css module
  client/src/components/pages/Error/error.module.css
  client/src/components/pages/Error/index.js
  client/src/components/pages/Error/style.css
  client/src/components/utils/Footer/Subscribe.js
  client/src/components/utils/Footer/footer.module.css
  client/src/components/utils/Footer/index.js
  client/src/components/utils/Loading/index.js
  client/src/components/utils/Loading/loading.module.css
  client/src/components/utils/index.js
Labels: Awaiting Review

#61 Navbar
  client/src/assets/FNLogoLightV2.png
  client/src/assets/FNLogodarkV2.png
  client/src/components/utils/Navbar/index.js
  client/src/components/utils/Navbar/navbar.module.css
  client/src/components/utils/index.js
Labels: Awaiting Review

#64 about page
  client/src/assets/FNLogoLightV2.png
  client/src/assets/FNLogodarkV2.png
  client/src/components/app/index.js
  client/src/components/pages/AboutUs/about.module.css
  client/src/components/pages/AboutUs/index.js
  client/src/components/pages/AboutUs/style.css
  client/src/components/utils/Navbar/navbar.module.css
  client/src/components/utils/index.js
Labels: Done

#67 under construction component
  client/src/components/app/index.js
  client/src/components/pages/AboutUs/index.js
  client/src/components/utils/UnderConstruction/index.js
  client/src/components/utils/UnderConstruction/underconstruction.module.css
  client/src/components/utils/index.js
Labels: Done

#69 Display data in a table
  client/src/components/pages/ViewBuildings/Table/index.js
  client/src/components/pages/ViewBuildings/index.js
Labels: Awaiting Review

#70 view buildings map
  client/public/index.html
  client/src/components/pages/ViewBuildings/Map.js
  client/src/components/pages/ViewBuildings/index.js
  client/src/components/pages/ViewBuildings/view.module.css
Labels: Done

#71 View buildings
  client/.gitignore
  client/public/index.html
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/pages/ViewBuildings/Map.js
  client/src/components/pages/ViewBuildings/Table.js
  client/src/components/pages/ViewBuildings/index.js
  client/src/components/pages/ViewBuildings/style.css
  client/src/components/pages/ViewBuildings/view.module.css
  client/src/components/utils/Navbar/navbar.module.css
Labels: approved

#76 position unique
  server/controllers/emptyBuildings/post.js
  test/emptyBuildings/get.test.js
  test/emptyBuildings/post.test.js
Labels: Awaiting Review

#78 reset value of subscribe
  client/src/components/app/style.css
  client/src/components/utils/Footer/Subscribe.js
Labels: approved

#73 Send email
  package-lock.json
  package.json
  server/controllers/mailList/index.js
  server/controllers/mailList/sendEmail.js
  server/controllers/mailList/template/index.html
Labels: Awaiting Review

#80 add map access token
  client/.gitignore
  client/src/components/pages/ViewBuildings/Map.js
Labels: approved

#82 edit readme file
  README.md
Labels: approved

#85 Home page
  client/src/components/pages/Home/ReportBuilding/Form/FirstStep.js
  client/src/components/pages/Home/ReportBuilding/Map/index.js
  client/src/components/pages/Home/index.js
Labels: Awaiting Review

#84 edit responsive styles for footer
  client/public/index.html
  client/public/logo.png
  client/src/components/app/style.css
  client/src/components/pages/Home/About/about.module.css
  client/src/components/pages/Home/Header/header.module.css
  client/src/components/pages/Home/Header/index.js
  client/src/components/pages/Home/ReportBuilding/Form/FirstStep.js
  client/src/components/pages/Home/ReportBuilding/Form/form.module.css
  client/src/components/pages/Home/ReportBuilding/Map/map.module.css
  client/src/components/pages/Home/ReportBuilding/report.module.css
  client/src/components/pages/ViewBuildings/Table.js
  client/src/components/pages/ViewBuildings/view.module.css
  client/src/components/utils/Footer/Subscribe.js
  client/src/components/utils/Footer/footer.module.css
  client/src/components/utils/Navbar/navbar.module.css
Labels: Awaiting Review

#87 Add loading for submit btn
  client/src/components/pages/Home/ReportBuilding/Form/ThirdStep.js
  client/src/components/pages/Home/ReportBuilding/Form/index.js
Labels: Awaiting Review

#89 refactor user testing
  client/src/assets/FNLogoLightV2.png
  client/src/assets/FNLogodarkV2.png
  client/src/assets/Fonts/BaskervilleMTStd-Bold.otf
  client/src/assets/Fonts/BaskervilleMTStd-BoldIt.otf
  client/src/assets/Fonts/BaskervilleMTStd-Italic.otf
  client/src/assets/Fonts/BaskervilleMTStd-Regular.otf
  client/src/assets/Fonts/BaskervilleMTStd-SemiBd.otf
  client/src/assets/Fonts/BaskervilleMTStd-SemiBdIt.otf
  client/src/assets/Fonts/Final Logo and Body Text.ai
  client/src/assets/Fonts/NexaBold.otf
  client/src/assets/Fonts/NexaLight.otf
  client/src/components/app/style.css
  client/src/components/pages/AboutUs/about.module.css
  client/src/components/pages/AboutUs/index.js
  client/src/components/pages/Home/About/about.module.css
  client/src/components/pages/Home/About/index.js
  client/src/components/pages/Home/Header/header.module.css
  client/src/components/pages/Home/Header/index.js
  client/src/components/pages/Home/ReportBuilding/Form/FirstStep.js
  client/src/components/pages/Home/ReportBuilding/Form/SecondStep.js
  client/src/components/pages/Home/ReportBuilding/Form/ThirdStep.js
  client/src/components/pages/Home/ReportBuilding/Form/form.module.css
  client/src/components/pages/Home/ReportBuilding/Form/index.js
  client/src/components/pages/Home/ReportBuilding/Map/index.js
  client/src/components/pages/Home/ReportBuilding/index.js
  client/src/components/pages/Home/ReportBuilding/report.module.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/ViewBuildings/Map.js
  client/src/components/pages/ViewBuildings/Table.js
  client/src/components/pages/ViewBuildings/index.js
  client/src/components/pages/ViewBuildings/view.module.css
  client/src/components/utils/Footer/footer.module.css
  client/src/components/utils/Footer/index.js
  client/src/components/utils/Navbar/index.js
  client/src/components/utils/Navbar/navbar.module.css
  server/models/queries/emptyBuildings.js
  server/uploads/building.png
  server/uploads/house.jpg
  server/validation/buildingSchema.js
  test/emptyBuildings/get.test.js
  test/emptyBuildings/post.test.js
Labels: Awaiting Review

#94 Edit style
  client/src/components/app/style.css
  client/src/components/pages/Home/Header/header.module.css
  client/src/components/pages/Home/ReportBuilding/Form/FirstStep.js
  client/src/components/pages/ViewBuildings/Table.js
  client/src/components/utils/Footer/Subscribe.js
  client/src/components/utils/Footer/footer.module.css
  client/src/components/utils/Footer/index.js
Labels: Awaiting Review

#96 add readme file
  README.md
Labels: Awaiting Review

#98 lazy import react
  client/package-lock.json
  client/package.json
  client/src/components/pages/Home/Header/header.module.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/ViewBuildings/index.js
  client/src/components/utils/Loading/index.js
Labels: Awaiting Review

#93 slider menu
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/pages/Home/ReportBuilding/Form/FirstStep.js
  client/src/components/pages/Home/ReportBuilding/Form/index.js
  client/src/components/pages/Home/ReportBuilding/report.module.css
  client/src/components/utils/Navbar/index.js
  client/src/components/utils/Navbar/navbar.module.css
  client/src/components/utils/SlideMenu/index.js
  client/src/components/utils/SlideMenu/menu.module.css
Labels: Awaiting Review

#103 Update README.md
  README.md
Labels: Awaiting Review

#105 fix bug for footer in error page
  client/src/components/app/style.css
  client/src/components/pages/Error/error.module.css
  client/src/components/pages/Error/index.js
  client/src/components/utils/Footer/index.js
Labels: Awaiting Review
